spring.application.name=authentication
server.port=8082
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/authentication_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
api.security.token.secret=${JWT_SECRET_KEY:mysecretkey}

spring.jpa.hibernate.ddl-auto=update